### ISSUE TITLE
Error on adding SDK to project

### ISSUE THREAD

**Issue by Emmarex** [NAXAM/mapbox-android-binding#10]
Have been getting this error since i added Naxm MapBox sdk to my xamarin project.

"/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java.lang.IllegalArgumentException: already added :  Lokio/AsyncTimeout"

Please how do i fix this? Once i remove this plugin and it other dependencies like Square.OkHttp3 and Square.OkIO my project builds successfully. I have MultiDex enabled already

**Comment by Emmarex** [comment]
Issue resolved. Removing modernhttpclient solved the issue

**Comment by tuyen-vuduc** [comment]
If you upgrade to latest version, you could keep ModernHttpClient. remove Naxam OkHttp packages will work.
