### ISSUE TITLE
App does not restart after closing it

### ISSUE THREAD

**Issue by Niach** [NAXAM/mapbox-android-binding#11]
If you swipe the app away in the recent apps, you cannot start the app again and it is stuck in the splashscreen.
I think maybe the mapbox service is not closed and prevents the mainactivity to start again. 
This behaviour also occures in the sample app.

**Comment by mdenkmaier** [comment]
Same on my side, cannot start the app again after closing it.
You can check it using your own sample application.

**Comment by tuyen-vuduc** [comment]
How do you guys say `closing it`? It works well at my end. (open <=> close)

**Comment by cschwengler** [comment]
Same, swipe the app away out of the recent apps(no explicit killing) and open it again -> infinite loop

**Comment by Niach** [comment]
I'm using it in a Fragment and did it like in your blog post:

`
public override void OnDestroyView()
        {
            mapView?.RemoveOnMapChangedListener(this);
			mapView?.OnDestroy();
			base.OnDestroyView();
        }
`

**Comment by tuyen-vuduc** [comment]
@cschwengler On which device did you face the issue?

@Niach Have you faced the same issue on my sample?

I didn't face any issues when closing app/opening app on simulator.

Cheers.

**Comment by tuyen-vuduc** [comment]
Hey,

I couldn't replicate your issue without more details.

Plz connect device and try to debug then get the logcat details.

Thanks.

**Comment by cschwengler** [comment]
Hey, i found whats going wrong. Its happening if you enabled the Mapbox TelemetryService.
Maybe you disabled it on your testing device. If its enabled and you try to restart the app, it hangs.

**Comment by Niach** [comment]
I made a video of your sample app: https://www.youtube.com/watch?v=AZg2D2dGa7U
After force-killing the app it works again, and if you disagree with the telemetry service it also works.

**Comment by tuyen-vuduc** [comment]
Plz check back v6.4 now.

**Comment by stephenmante** [comment]
App freezes due to fragment dispose related problem. This issue occur in Xamarin Forms. I tried the same approach like what amay077 did in Xamarin.Forms.GoogleMaps in creating the view that can be found in this link https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/MapRenderer.cs#L119 and it solves the problem.
