### ISSUE TITLE
Building extrusion

### ISSUE THREAD

**Issue by Emixam23** [NAXAM/mapbox-android-binding#13]
Hey !

I would like to know if your package provides 3D building extrusion?

Thanks,

Max

**Comment by tuyen-vuduc** [comment]
@Emixam23 

It's binding library for Mapbox native SDK, so what the native version provides will be there.

Cheers.

**Comment by Emixam23** [comment]
Perfect !

I will give it a try then, thank you :)

**Comment by Emixam23** [comment]
Hey !

I did give a try and... I am close but still not working. I am trying to translate this piece of Java:

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/PopulationDensityExtrusionActivity.java

However, I can't find the `interpolate` function, it's the only part I couldn't code so far...

Thanks for any help !

**Comment by tuyen-vuduc** [comment]
Please check out latest version

https://www.nuget.org/packages/Com.Mapbox.Maps.Android
