### ISSUE TITLE
Instructions on how to create new version of mapbox sdk

### ISSUE THREAD

**Issue by F0rc0sigan** [NAXAM/mapbox-android-binding#14]
Hi,

Thanks for great work. Can you share details on how do you make new release of your binding. I want to try to help and make next release so it is up-to-date.

Thanks.

**Comment by tuyen-vuduc** [comment]
Hi @F0rc0sigan ,

Great! 

If you never do binding library before, plz read the guide from Xamarin [here](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/).

Then you will get to know how to upgrade this binding library.

Cheers.

**Comment by F0rc0sigan** [comment]
Hi @tuyen-vuduc,

I created binding before. But i had jar file for that. Where can i get latest aar file? I see some scripts in repository, is there anything that can automate using them?

Regards.

**Comment by tuyen-vuduc** [comment]
HI @F0rc0sigan @Emixam23,

Thank you very much for your interests and your willingness.

The binding creating isn't that complicated, except it requires to create multiple binding libraries at once and in order.

The AAR file could be found on mvnrepository.com.

I will try to write some instructions on how to run the automation script. At this time, it isn't straight forward.

Cheers.

**Comment by F0rc0sigan** [comment]
Hello @tuyen-vuduc,

Could you tell order in which need to biuild binding libraries?

Regards,
Dima

**Comment by tuyen-vuduc** [comment]
You should go based on dependency tree of Mapbox libraries. It's all clear on https://mvnrepository.com/

Cheers.
