### ISSUE TITLE
Could you push new mapbox version to nuget, please

### ISSUE THREAD

**Issue by F0rc0sigan** [NAXAM/mapbox-android-binding#15]

**Comment by wollac11** [comment]
I would like to second this. Mapbox 5.5.2 has some performance issues with pinch/zoom which are seemingly fixed in 6.2.0 but there is no NuGet package for Mapbox 6.2.0 or some of its dependencies (such as Mapbox-Java-Geojson 3.0.1). Please could you push updated NuGet packages for these.

**Comment by tuyen-vuduc** [comment]
It's now 6.4 already.
