### ISSUE TITLE
Offline mapbox?

### ISSUE THREAD

**Issue by asterixorobelix** [NAXAM/mapbox-android-binding#17]
Hi, thanks for the xamarin binding. Is there a way to download areas of the map for offline use like the native library? https://www.mapbox.com/android-docs/plugins/overview/offline/

**Comment by tuyen-vuduc** [comment]
You will need to create binding library for that plugin if you want to use it. Otherwise, offline function is currently working with Mapbox SDK, plz check out how to use it in Mapbox for Xamarin.Forms project.
