### ISSUE TITLE
Android offline 

### ISSUE THREAD

**Issue by stefangstrein1** [NAXAM/mapbox-android-binding#19]
In android the map is not initialized when starting the app in airplane mode. Seems that the style is not set correctly. 
I downloaded Naxam.mapbox.Platform.Droid and changed MapViewFragment.cs 

public override void OnViewCreated(View view, Bundle savedInstanceState)
        {
            base.OnViewCreated(view, savedInstanceState);

            MapView = view as MapView;
            // here the style is set and then the map is as well working offline from start
            MapView.SetStyleUrl("mapbox://styles/mapbox/streets-v9");
            MapView?.AddOnMapChangedListener(this);
        }

Is this approach correct ?

**Comment by tuyen-vuduc** [comment]
Hi,

Could you double check the latest version as well as the native version?

Cheers.
