### ISSUE TITLE
Return type of functions in MarkerOptions are wrong

### ISSUE THREAD

**Issue by charlenni** [NAXAM/mapbox-android-binding#4]
MarkerOptions is a builder for Markers. It is derived from BaseMarkerOptions<U extends Marker,T extends BaseMarkerOptions<U,T>> and should return always T, so that the following is possible:

````
var markerOpts = new MarkerOptions().SetTitle("Title").SetSnippet("Snippet");
````

This isn't possible, because all functions (SetTitle(), SetSnippet() and so on) return Java.Lang.Object.

**Comment by charlenni** [comment]
The same for MarkerViewOptions.

**Comment by kanvuduc** [comment]
Great finding. We will update the binding to correct this.
