### ISSUE TITLE
An MGLAnnotationImage backed annotation is not visible if it is animated off-screen and then on-screen

### ISSUE THREAD

**Issue by alisolutions** [NAXAM/mapbox-android-binding#8]
While animating the marker, when marker goes beyond the screen, it remains hide.
The following link is showing the issue.
https://www.dropbox.com/s/7auffog9x9yiuwv/IMG_4792.m4v?dl=0

I am using Marker annotation, in Xamarin Android.
Do you need the code which i am using to animate the Marker?

Following is the code to add Marker,
marker = Map.AddMarker(new MarkerViewOptions().SetPosition(route[0]));

and following is the code which I am using for Animation.
https://gist.github.com/broady/6314689

**Comment by tuyen-vuduc** [comment]
@alisolutions Have you checked with native Java code?
