### ISSUE TITLE
Any plans to update to last sdk version (5.2.0) in a near future?

### ISSUE THREAD

**Issue by rayita** [NAXAM/mapbox-android-binding#9]
Any plans to update to last sdk version (5.2.0) in a near future?

Any plans to create navigation sdk bindings to?

Thanks

**Comment by tuyen-vuduc** [comment]
Sure, there will be.

It does really take time to create/maintain the binding libraries.

It'll be quicker if there are backs from the one who use our binding libraries like you. 

Cheers.

**Comment by tuyen-vuduc** [comment]
Commit d7d0810
